//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamExplosion.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamExplosion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email verification.
        /// </summary>
        public static string accountCreationblEmailVerTitle {
            get {
                return ResourceManager.GetString("accountCreationblEmailVerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred while creating the account.
        /// </summary>
        public static string accountCreationCreationError {
            get {
                return ResourceManager.GetString("accountCreationCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email and gamertag already in use.
        /// </summary>
        public static string accountCreationEmailAndGamertagTaken {
            get {
                return ResourceManager.GetString("accountCreationEmailAndGamertagTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provided data already exists in another account.
        /// </summary>
        public static string accountCreationExistingData {
            get {
                return ResourceManager.GetString("accountCreationExistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been created successfully.
        /// </summary>
        public static string accountCreationLblAccountCreated {
            get {
                return ResourceManager.GetString("accountCreationLblAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending email, check if it is spelled correctly and your internet connectioni.
        /// </summary>
        public static string accountCreationLblEmailError {
            get {
                return ResourceManager.GetString("accountCreationLblEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code sent to your email.
        /// </summary>
        public static string accountCreationLblEmailVerification {
            get {
                return ResourceManager.GetString("accountCreationLblEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The gamertag already exists.
        /// </summary>
        public static string accountCreationLblExistingGamertag {
            get {
                return ResourceManager.GetString("accountCreationLblExistingGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your gamertag must not start with Guest.
        /// </summary>
        public static string accountCreationLblGamertagNotGuest {
            get {
                return ResourceManager.GetString("accountCreationLblGamertagNotGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email.
        /// </summary>
        public static string accountCreationLblInvalidEmail {
            get {
                return ResourceManager.GetString("accountCreationLblInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only letters and numbers.
        /// </summary>
        public static string accountCreationLblInvalidGamertag {
            get {
                return ResourceManager.GetString("accountCreationLblInvalidGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It must start with a letter.
        /// </summary>
        public static string accountCreationLblInvalidGamertagInitial {
            get {
                return ResourceManager.GetString("accountCreationLblInvalidGamertagInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name format incorrect.
        /// </summary>
        public static string accountCreationLblInvalidName {
            get {
                return ResourceManager.GetString("accountCreationLblInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email is linked to another account.
        /// </summary>
        public static string accountCreationLblLinkedEmail {
            get {
                return ResourceManager.GetString("accountCreationLblLinkedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing information, complete required fields.
        /// </summary>
        public static string accountCreationLblMissingInformation {
            get {
                return ResourceManager.GetString("accountCreationLblMissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked players.
        /// </summary>
        public static string blockAndFriendsListLblBlockedUsers {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unfriend.
        /// </summary>
        public static string blockAndFriendsListLblDeleteFriend {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend.
        /// </summary>
        public static string blockAndFriendsListLblFriend {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to unblock this player?.
        /// </summary>
        public static string blockAndFriendsListLblQuestion {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unblock player.
        /// </summary>
        public static string blockAndFriendsListLblUnblock {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to unfriend this player?.
        /// </summary>
        public static string blockAndFriendsListLblUnfriendQuestion {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblUnfriendQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has lost.
        /// </summary>
        public static string boardLblAnotherPlayerLost {
            get {
                return ResourceManager.GetString("boardLblAnotherPlayerLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You obtained.
        /// </summary>
        public static string boardLblCardObtained {
            get {
                return ResourceManager.GetString("boardLblCardObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a requested you a card.
        /// </summary>
        public static string boardLblCardRequested {
            get {
                return ResourceManager.GetString("boardLblCardRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your next turn will be double.
        /// </summary>
        public static string boardLblDoubleTurn {
            get {
                return ResourceManager.GetString("boardLblDoubleTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve lost.
        /// </summary>
        public static string boardLblPlayerLost {
            get {
                return ResourceManager.GetString("boardLblPlayerLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use a re registration to win against exam bomb card or you&apos;ll lose a hit point.
        /// </summary>
        public static string boardLblReregistrationNeeded {
            get {
                return ResourceManager.GetString("boardLblReregistrationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has disconnected.
        /// </summary>
        public static string boardLblUserDisconnected {
            get {
                return ResourceManager.GetString("boardLblUserDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have lost a life unless you can re-register..
        /// </summary>
        public static string catalogueLblExamBombDescription {
            get {
                return ResourceManager.GetString("catalogueLblExamBombDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End your turn without taking a card..
        /// </summary>
        public static string catalogueLblExemptDescription {
            get {
                return ResourceManager.GetString("catalogueLblExemptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player of your choice gives you a card..
        /// </summary>
        public static string catalogueLblFavorDescription {
            get {
                return ResourceManager.GetString("catalogueLblFavorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your turn is passed to the next person..
        /// </summary>
        public static string catalogueLblLeftTeamDescription {
            get {
                return ResourceManager.GetString("catalogueLblLeftTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You recover from a exam bomb, you don&apos;t lose your life.
        /// </summary>
        public static string catalogueLblReRegistrationDescription {
            get {
                return ResourceManager.GetString("catalogueLblReRegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You shuffle the cards.
        /// </summary>
        public static string catalogueLblShuffleDescription {
            get {
                return ResourceManager.GetString("catalogueLblShuffleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You take a card from the bottom of the stack.
        /// </summary>
        public static string catalogueLblTakeBelowDescription {
            get {
                return ResourceManager.GetString("catalogueLblTakeBelowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put together two cards from the same teacher and a player must give you a card..
        /// </summary>
        public static string catalogueLblTeacherDescription {
            get {
                return ResourceManager.GetString("catalogueLblTeacherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalogue.
        /// </summary>
        public static string catalogueLblTitle {
            get {
                return ResourceManager.GetString("catalogueLblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can see the next 3 cards of the Stack without shuffling..
        /// </summary>
        public static string catalogueLblViewFutureDescription {
            get {
                return ResourceManager.GetString("catalogueLblViewFutureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code is incorrect..
        /// </summary>
        public static string emailVerificationLblIncorrectCode {
            get {
                return ResourceManager.GetString("emailVerificationLblIncorrectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not friend this player.
        /// </summary>
        public static string endGameLblAddFriendError {
            get {
                return ResourceManager.GetString("endGameLblAddFriendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while friending this person.
        /// </summary>
        public static string endGameLblAddFriendErrorDescription {
            get {
                return ResourceManager.GetString("endGameLblAddFriendErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend added.
        /// </summary>
        public static string endGameLblAddFriendTitle {
            get {
                return ResourceManager.GetString("endGameLblAddFriendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while blocking.
        /// </summary>
        public static string endGameLblBlockError {
            get {
                return ResourceManager.GetString("endGameLblBlockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while blocking this player.
        /// </summary>
        public static string endGameLblBlockErrorDescription {
            get {
                return ResourceManager.GetString("endGameLblBlockErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player blocked.
        /// </summary>
        public static string endGameLblBlockTitle {
            get {
                return ResourceManager.GetString("endGameLblBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This player can not be your friend because it&apos;s blocked.
        /// </summary>
        public static string endGameLblCouldNotBeFriends {
            get {
                return ResourceManager.GetString("endGameLblCouldNotBeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You added this player as a friend.
        /// </summary>
        public static string endGameLblPlayerAdded {
            get {
                return ResourceManager.GetString("endGameLblPlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You blocked this player.
        /// </summary>
        public static string endGameLblPlayerBlocked {
            get {
                return ResourceManager.GetString("endGameLblPlayerBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string endgameLblPlayerObtainingError {
            get {
                return ResourceManager.GetString("endgameLblPlayerObtainingError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblGamertagNotFound {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblGamertagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblUserFoundError {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblUserFoundError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblFriendAddError{
            get {
                return ResourceManager.GetString("blockAndFriendsListLblFriendAddError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblFriendAddedDescription {
            get {
                return ResourceManager.GetString("blockAndFriendsListLblFriendAddedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblFriendAdded{
            get {
                return ResourceManager.GetString("blockAndFriendsListLblFriendAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblAlreadyFriends{
            get {
                return ResourceManager.GetString("blockAndFriendsListLblAlreadyFriends", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblAlreadyFriendsDescription{
            get {
                return ResourceManager.GetString("blockAndFriendsListLblAlreadyFriendsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving game results, please let us know!.
        /// </summary>
        public static string blockAndFriendsListLblSearch{
            get {
                return ResourceManager.GetString("blockAndFriendsListLblSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You reported this player.
        /// </summary>
        public static string endGameLblPlayerReported {
            get {
                return ResourceManager.GetString("endGameLblPlayerReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report error.
        /// </summary>
        public static string endGameLblReportError {
            get {
                return ResourceManager.GetString("endGameLblReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while reporting this player.
        /// </summary>
        public static string endGameLblReportErrorDescription {
            get {
                return ResourceManager.GetString("endGameLblReportErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player reported.
        /// </summary>
        public static string endGameLblReportTitle {
            get {
                return ResourceManager.GetString("endGameLblReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defeat.
        /// </summary>
        public static string endGameLblYouLose {
            get {
                return ResourceManager.GetString("endGameLblYouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganaste.
        /// </summary>
        public static string endGameLblYouWin {
            get {
                return ResourceManager.GetString("endGameLblYouWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de partida.
        /// </summary>
        public static string gameCodeLblEnterCode {
            get {
                return ResourceManager.GetString("gameCodeLblEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code entered does not belong to any available lobby.
        /// </summary>
        public static string gameCodeLblInexistentLobby {
            get {
                return ResourceManager.GetString("gameCodeLblInexistentLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inexistent lobby.
        /// </summary>
        public static string gameCodeLblInexistentLobbyTitle {
            get {
                return ResourceManager.GetString("gameCodeLblInexistentLobbyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code.
        /// </summary>
        public static string gameCodeLblTitle {
            get {
                return ResourceManager.GetString("gameCodeLblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winner.
        /// </summary>
        public static string gameLblWinner {
            get {
                return ResourceManager.GetString("gameLblWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max HP.
        /// </summary>
        public static string gamePreferencesLblMaxHp {
            get {
                return ResourceManager.GetString("gamePreferencesLblMaxHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max players.
        /// </summary>
        public static string gamePreferencesLblMaxPlayers {
            get {
                return ResourceManager.GetString("gamePreferencesLblMaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time per turn.
        /// </summary>
        public static string gamePreferencesLblTime {
            get {
                return ResourceManager.GetString("gamePreferencesLblTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn.
        /// </summary>
        public static string gameTurn {
            get {
                return ResourceManager.GetString("gameTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string globalBtnCancel {
            get {
                return ResourceManager.GetString("globalBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string globalBtnCreate {
            get {
                return ResourceManager.GetString("globalBtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string globalBtnJoin {
            get {
                return ResourceManager.GetString("globalBtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string globalBtnLeave {
            get {
                return ResourceManager.GetString("globalBtnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string globalBtnPlay {
            get {
                return ResourceManager.GetString("globalBtnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        public static string globalLblAccount {
            get {
                return ResourceManager.GetString("globalLblAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code.
        /// </summary>
        public static string globalLblCode {
            get {
                return ResourceManager.GetString("globalLblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the server..
        /// </summary>
        public static string globalLblCommunicationException {
            get {
                return ResourceManager.GetString("globalLblCommunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hecho.
        /// </summary>
        public static string globalLblDone {
            get {
                return ResourceManager.GetString("globalLblDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalLblEmail {
            get {
                return ResourceManager.GetString("globalLblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string globalLblError {
            get {
                return ResourceManager.GetString("globalLblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exam bomb.
        /// </summary>
        public static string globalLblExamBombCard {
            get {
                return ResourceManager.GetString("globalLblExamBombCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exempt.
        /// </summary>
        public static string globalLblExemptCard {
            get {
                return ResourceManager.GetString("globalLblExemptCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred with the server.
        /// </summary>
        public static string globalLblFaultException {
            get {
                return ResourceManager.GetString("globalLblFaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor.
        /// </summary>
        public static string globalLblFavorCard {
            get {
                return ResourceManager.GetString("globalLblFavorCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamertag.
        /// </summary>
        public static string globalLblGamertag {
            get {
                return ResourceManager.GetString("globalLblGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        public static string globalLblLastname {
            get {
                return ResourceManager.GetString("globalLblLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leaderboard.
        /// </summary>
        public static string globalLblLeaderboard {
            get {
                return ResourceManager.GetString("globalLblLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left team.
        /// </summary>
        public static string globalLblLeftTeamCard {
            get {
                return ResourceManager.GetString("globalLblLeftTeamCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string globalLblName {
            get {
                return ResourceManager.GetString("globalLblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required.
        /// </summary>
        public static string globalLblNotBlanks {
            get {
                return ResourceManager.GetString("globalLblNotBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalLblPassword {
            get {
                return ResourceManager.GetString("globalLblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords must be the same.
        /// </summary>
        public static string globalLblPasswordCoincidence {
            get {
                return ResourceManager.GetString("globalLblPasswordCoincidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8 to 20 characters.
        /// </summary>
        public static string globalLblPasswordLength {
            get {
                return ResourceManager.GetString("globalLblPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string globalLblPlayers {
            get {
                return ResourceManager.GetString("globalLblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat password.
        /// </summary>
        public static string globalLblRepeatPassword {
            get {
                return ResourceManager.GetString("globalLblRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string globalLblSettings {
            get {
                return ResourceManager.GetString("globalLblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        public static string globalLblShow {
            get {
                return ResourceManager.GetString("globalLblShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shuffle.
        /// </summary>
        public static string globalLblShuffleCard {
            get {
                return ResourceManager.GetString("globalLblShuffleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special characters allowed: #,$,%,&amp;,!.
        /// </summary>
        public static string globalLblSpecialCharacters {
            get {
                return ResourceManager.GetString("globalLblSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take from below.
        /// </summary>
        public static string globalLblTakeBelowCard {
            get {
                return ResourceManager.GetString("globalLblTakeBelowCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teacher A.
        /// </summary>
        public static string globalLblTeacherACard {
            get {
                return ResourceManager.GetString("globalLblTeacherACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teacher M.
        /// </summary>
        public static string globalLblTeacherMCard {
            get {
                return ResourceManager.GetString("globalLblTeacherMCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teacher O.
        /// </summary>
        public static string globalLblTeacherOCard {
            get {
                return ResourceManager.GetString("globalLblTeacherOCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teacher R.
        /// </summary>
        public static string globalLblTeacherRCard {
            get {
                return ResourceManager.GetString("globalLblTeacherRCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teacher S.
        /// </summary>
        public static string globalLblTeacherSCard {
            get {
                return ResourceManager.GetString("globalLblTeacherSCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection to the server has expired.
        /// </summary>
        public static string globalLblTimeoutException {
            get {
                return ResourceManager.GetString("globalLblTimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View the future.
        /// </summary>
        public static string globalLblViewFutureCard {
            get {
                return ResourceManager.GetString("globalLblViewFutureCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Re registration.
        /// </summary>
        public static string globalReRegistrationCard {
            get {
                return ResourceManager.GetString("globalReRegistrationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string homeLblLogout {
            get {
                return ResourceManager.GetString("homeLblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        public static string komalliBtnBuy {
            get {
                return ResourceManager.GetString("komalliBtnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use.
        /// </summary>
        public static string komalliBtnUse {
            get {
                return ResourceManager.GetString("komalliBtnUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Now your cards look like this.
        /// </summary>
        public static string komalliLblAccessoryInUse {
            get {
                return ResourceManager.GetString("komalliLblAccessoryInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pack in use.
        /// </summary>
        public static string komalliLblAccessoryInUseTitle {
            get {
                return ResourceManager.GetString("komalliLblAccessoryInUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cap.
        /// </summary>
        public static string komalliLblCap {
            get {
                return ResourceManager.GetString("komalliLblCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graduated.
        /// </summary>
        public static string komalliLblGraduated {
            get {
                return ResourceManager.GetString("komalliLblGraduated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hat.
        /// </summary>
        public static string komalliLblHat {
            get {
                return ResourceManager.GetString("komalliLblHat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to win more games to purchase this pack.
        /// </summary>
        public static string komalliLblInsuficientPoints {
            get {
                return ResourceManager.GetString("komalliLblInsuficientPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not enough points.
        /// </summary>
        public static string komalliLblInsuficientPointsTitle {
            get {
                return ResourceManager.GetString("komalliLblInsuficientPointsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while opening Komalli, please contact us!.
        /// </summary>
        public static string komalliLblLoadingPackagesError {
            get {
                return ResourceManager.GetString("komalliLblLoadingPackagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Now you can use it to see cards like this in your games.
        /// </summary>
        public static string komalliLblPackPurchased {
            get {
                return ResourceManager.GetString("komalliLblPackPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pack purchased.
        /// </summary>
        public static string komalliLblPackPurchasedTitle {
            get {
                return ResourceManager.GetString("komalliLblPackPurchasedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Points.
        /// </summary>
        public static string komalliLblPoints {
            get {
                return ResourceManager.GetString("komalliLblPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while obtaining the leaderboard.
        /// </summary>
        public static string leaderboardLblObtainingError {
            get {
                return ResourceManager.GetString("leaderboardLblObtainingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only Friends.
        /// </summary>
        public static string leaderboardLblOnlyFriends {
            get {
                return ResourceManager.GetString("leaderboardLblOnlyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string leaderboardLblWins {
            get {
                return ResourceManager.GetString("leaderboardLblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string lobbyBtnStart {
            get {
                return ResourceManager.GetString("lobbyBtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string lobbyLblChat {
            get {
                return ResourceManager.GetString("lobbyLblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code.
        /// </summary>
        public static string lobbyLblGameTitle {
            get {
                return ResourceManager.GetString("lobbyLblGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string lobbyLblPlayers {
            get {
                return ResourceManager.GetString("lobbyLblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All players must be ready to start.
        /// </summary>
        public static string lobbyLblPlayersArentReady {
            get {
                return ResourceManager.GetString("lobbyLblPlayersArentReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait.
        /// </summary>
        public static string lobbyLblWait {
            get {
                return ResourceManager.GetString("lobbyLblWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string loginBtnLogin {
            get {
                return ResourceManager.GetString("loginBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account is inactive due to another player&apos;s reports..
        /// </summary>
        public static string loginLblAccountInactive {
            get {
                return ResourceManager.GetString("loginLblAccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not login.
        /// </summary>
        public static string loginLblCannotLogin {
            get {
                return ResourceManager.GetString("loginLblCannotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamertag and/or password are incorrect.
        /// </summary>
        public static string loginLblInvalidCredentials {
            get {
                return ResourceManager.GetString("loginLblInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string loginLblTitle {
            get {
                return ResourceManager.GetString("loginLblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string settingsBtnSave {
            get {
                return ResourceManager.GetString("settingsBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string settingsLblCurrentPassword {
            get {
                return ResourceManager.GetString("settingsLblCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password does not match this.
        /// </summary>
        public static string settingsLblCurrentPasswordWrong {
            get {
                return ResourceManager.GetString("settingsLblCurrentPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong password.
        /// </summary>
        public static string settingsLblCurrentPasswordWrongTitle {
            get {
                return ResourceManager.GetString("settingsLblCurrentPasswordWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing fields.
        /// </summary>
        public static string settingsLblMissingFields {
            get {
                return ResourceManager.GetString("settingsLblMissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct the fields that are necessary.
        /// </summary>
        public static string settingsLblMissingFieldsDescription {
            get {
                return ResourceManager.GetString("settingsLblMissingFieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string settingsLblNewPassword {
            get {
                return ResourceManager.GetString("settingsLblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been updated.
        /// </summary>
        public static string settingsLblPasswordUpdated {
            get {
                return ResourceManager.GetString("settingsLblPasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password updated.
        /// </summary>
        public static string settingsLblPasswordUpdatedTitle {
            get {
                return ResourceManager.GetString("settingsLblPasswordUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while updating your password.
        /// </summary>
        public static string settingsLblPasswordUpdateError {
            get {
                return ResourceManager.GetString("settingsLblPasswordUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code sent to your email.
        /// </summary>
        public static string signUpLblCodeSent {
            get {
                return ResourceManager.GetString("signUpLblCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create player account.
        /// </summary>
        public static string startBtnCreateAccount {
            get {
                return ResourceManager.GetString("startBtnCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest.
        /// </summary>
        public static string startBtnGuest {
            get {
                return ResourceManager.GetString("startBtnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exam Explosion.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
